### ISSUE TITLE
Issue with reentrace of promises

### ISSUE THREAD

**Issue by miz-online** [web-atoms/xamarin-v8#2]
Hi,
first of all THANK YOU for the native integration of V8 into Xamarin for Android.
we have a project that integrates JS engines on Android, iOS and UWP. For Android we currently use the java bindings from eclipsesource. But -as you also mentioned - it is too much overhead to have this java wrapper (beside it gives us not enough control).
So I was happy to find your project and integrated it. it works very well, beside one test case that just crashes the app.

this is the test I am running:
```
var test= require('testAsync/v1'); //gets an interface wrapper for a c# function
test.someMethodWhichCallsAnAsyncFunction( //our wrapped, async C# function
  function(){ return new Promise(
    function(resolve,reject){reject('Exception')});})
      .then(function() { test.setResult('should not happen'); }, function(error) { test.setResult(error.message); 
  });
```

the code runs in the v8 engine
the method 'someMethodWhichCallsAnAsyncFunction calls a js function that returns a promise. the C# function itself is wrapped in some js wrapper code that constructs a promise itself and then calls the c# function. when the function returns, it calls back into js code and calls 'reject' on the promise that wrapped the c# function.
this call crashes the app:

```
=================================================================
	Native Crash Reporting10-06 20:55:35.296 W/Testing.Androi(32736): 0xebadde09 skipped times: 0

=================================================================
Got a SEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
	  at <unknown> <0xffffffff>
	  at Xamarin.Android.V8.JSContext:V8Context_InvokeFunction <0x00007>
	  at Xamarin.Android.V8.JSValue:InvokeFunction <0x001ff>
```

we are using our own wrapper code (instead the one for promises in your library) because we need to support different engines (e.g. javascriptcore on iOS because we want to distribute via app store).

I know its hard to judge without having the exact code, but can you make sense of the issue?

It is definitively related with calling the 'reject' on the promise generated to wrap our async c# call. if resolve is called, everything is fine. I will try to make a simplified repo if possible.

thank you very much for your feedback
Michael

**Comment by ackava** [comment]
Which version you are using, have you looked at https://www.webatoms.in ? We have created complete UI Framework with JSX (with full support for iOS along with JavaScriptCore).

Web Atoms takes care of multithreaded access and it marshals `Task<T>` easily into promise and from promise to `Task<T>`.

**Comment by ackava** [comment]
@miz-online 

Clr delegates are weak, it means if you do not store it's reference in some field, they get garbage collected, we had similar issue in our some of the code.
